# Generated by Django 4.1.3 on 2022-12-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='time_date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
